refactor: documentation for agent setup section
credebl/docs pull request #34
Opened 2024-09-09 11:28 UTC by bhavanakarwade

### What?
- Refactored document for agent setup section

2024-09-09 11:38 UTC, pranalidhanavade approved these changes
LG

2024-09-16 05:54 UTC, GHkrishna requested changes

2024-09-16 05:54 UTC, GHkrishna commented on src/content/docs/en/contributorsguide/setup/agent/envsetup.md
> +**BCOVRIN_TEST_GENESIS=** `{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vL
```suggestion
BCOVRIN_TEST_GENESIS= `{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vLuL3zU88KyeAYcHfsih3He6UHcXDxcaecHVz6jhCYz1P2UZn2bDVruL5wXpehgBfBaLKm3Ba","blskey_pop":"RahHYiCvoNCtPTrVtP7nMC5eTYrsUA8WjXbdhNc8debh1agE9bGiJxWBXYNFbnJXoXhWFMvyqhqhRoq737YQemH5ik9oL7R4NTTCz2LEZhkgLJzB3QRQqJyBNyv7acbdHrAT8nQ9UkLbaVL9NBpnWXBTw4LEMePaSHEw66RzPNdAX1","client_ip":"138.197.138.255","client_port":9702,"node_ip":"138.197.138.255","node_port":9701,"services":["VALIDATOR"]},"dest":"Gw6pDLhcBcoQesN72qfotTgFa7cbuqZpkX3Xo6pLhPhv"},"metadata":{"from":"Th7MpTaRZVRYnPiabds81Y"},"type":"0"},"txnMetadata":{"seqNo":1,"txnId":"fea82e10e894419fe2bea7d96296a6d46f50f93f9eeda954ec461b2ed2950b62"},"ver":"1"}
```

2024-09-16 05:54 UTC, GHkrishna commented on src/content/docs/en/contributorsguide/setup/agent/references.md
> +- To know more about <a href = "https://aca-py.org/latest/">AFJ Controller</a>
```suggestion
- To know more about <a href = "https://aca-py.org/latest/">ACA-py</a>
```

2024-09-16 05:57 UTC, bhavanakarwade commented on src/content/docs/en/contributorsguide/setup/agent/envsetup.md
> +**BCOVRIN_TEST_GENESIS=** `{"reqSignature":{},"txn":{"data":{"data":{"alias":"Node1","blskey":"4N8aUNHSgjQVgkpm8nhNEfDf6txHznoYREg9kirmJrkivgL4oSEimFF6nsQ6M41QvhM2Z33nves5vfSn9n1UwNFJBYtWVnHYMATn76vL
Resolved

2024-09-16 05:57 UTC, bhavanakarwade commented on src/content/docs/en/contributorsguide/setup/agent/references.md
> +- To know more about <a href = "https://aca-py.org/latest/">AFJ Controller</a>
Resolved

2024-09-16 06:14 UTC, GHkrishna approved these changes

2024-09-16 06:18 UTC, KulkarniShashank approved these changes

2024-09-16 06:19 UTC, merged