docs: improved contents
credebl/docs pull request #7
Opened 2023-09-15 22:01 UTC by ajile-in

- Improved sidebar menu
- updated starlight package to latest
- improved docs contents

2023-09-16 02:41 UTC, vivekayanworks requested changes

2023-09-16 02:41 UTC, vivekayanworks commented on src/content/docs/en/guides/local-setup-using-docker.md
>  description: A reference page in my new CREDEBL docs site.
We need to modify this content.

2023-09-16 02:41 UTC, vivekayanworks commented on src/content/docs/en/guides/local-setup-using-npm.md
>  description: A reference page in my new CREDEBL docs site.
Please modify the content.

2023-09-17 13:37 UTC, ajile-in commented on src/content/docs/en/guides/local-setup-using-docker.md
>  description: A reference page in my new CREDEBL docs site.
@vivekayanworks - Can you suggest please the specific changes?

2023-09-19 02:08 UTC, vivekayanworks commented on src/content/docs/en/guides/local-setup-using-docker.md
>  description: A reference page in my new CREDEBL docs site.
@ajile-in In the description we need to remove "my new".

2023-09-19 02:08 UTC, vivekayanworks commented on src/content/docs/en/guides/local-setup-using-npm.md
>  description: A reference page in my new CREDEBL docs site.
@ajile-in In the description we need to remove "my new".

2023-12-15 08:19 UTC, merged